In [1]:
import numpy as np
from sklearn.metrics import confusion_matrix

In [6]:
true = [1, 1, 0, 1, 1, 0, 0, 1, 0, 1]
pred = [1, 1, 1, 0, 1, 0, 0, 1, 1, 1]

In [7]:
confusion_matrix(true, pred)

array([[2, 2],
       [1, 5]])

In [36]:
cm = np.array([[95, 5], 
                 [12, 88]])

cm

array([[95,  5],
       [12, 88]])

In [37]:
accr = round(100*np.trace(cm) / np.sum(cm), 2)
spec = round(100*cm[0, 0] / np.sum(cm[0, :]), 2)
npv = round(100*cm[0, 0] / np.sum(cm[:, 0]), 2)

sen = np.zeros(len(cm))
ppv = np.zeros(len(cm))

for i in range(1, len(cm)):
    sen[i] = np.sum(cm[i, :])*(cm[i, i] / np.sum(cm[i, :]))
    ppv[i] = np.sum(cm[:, i])*(cm[i, i] / np.sum(cm[:, i]))
    
sen = round(100*np.sum(sen)/np.sum(cm[1:, :]), 2)
ppv = round(100*np.sum(ppv)/np.sum(cm[:, 1:]), 2)

print(accr, sen, spec, npv, ppv)

91.5 88.0 95.0 88.79 94.62


In [39]:
cm = np.array([[100, 0], 
                 [100, 0]])

accr = round(100*np.trace(cm) / np.sum(cm), 2)
spec = round(100*cm[0, 0] / np.sum(cm[0, :]), 2)
npv = round(100*cm[0, 0] / np.sum(cm[:, 0]), 2)

sen = np.zeros(len(cm))
ppv = np.zeros(len(cm))

for i in range(1, len(cm)):
    sen[i] = np.sum(cm[i, :])*(cm[i, i] / np.sum(cm[i, :]))
    ppv[i] = np.sum(cm[:, i])*(cm[i, i] / np.sum(cm[:, i]))
    
sen = round(100*np.sum(sen)/np.sum(cm[1:, :]), 2)
ppv = round(100*np.sum(ppv)/np.sum(cm[:, 1:]), 2)

print(accr, sen, spec, npv, ppv)

50.0 0.0 100.0 50.0 nan


/home/yunseob/Pytorch/lib/python3.5/site-packages/ipykernel_launcher.py:13: RuntimeWarning: invalid value encountered in long_scalars
  del sys.path[0]


In [41]:
cm = np.array([[0, 100], 
                 [0, 100]])

accr = round(100*np.trace(cm) / np.sum(cm), 2)
spec = round(100*cm[0, 0] / np.sum(cm[0, :]), 2)
npv = round(100*cm[0, 0] / np.sum(cm[:, 0]), 2)

sen = np.zeros(len(cm))
ppv = np.zeros(len(cm))

for i in range(1, len(cm)):
    sen[i] = np.sum(cm[i, :])*(cm[i, i] / np.sum(cm[i, :]))
    ppv[i] = np.sum(cm[:, i])*(cm[i, i] / np.sum(cm[:, i]))
    
sen = round(100*np.sum(sen)/np.sum(cm[1:, :]), 2)
ppv = round(100*np.sum(ppv)/np.sum(cm[:, 1:]), 2)

print(accr, sen, spec, npv, ppv)

50.0 100.0 0.0 nan 50.0


/home/yunseob/Pytorch/lib/python3.5/site-packages/ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in long_scalars
  


In [47]:
cm = np.array([[92, 5, 3], 
               [10, 88, 2], 
               [3, 7, 90]])

accr = round(100*np.trace(cm) / np.sum(cm), 2)
spec = round(100*cm[0, 0] / np.sum(cm[0, :]), 2)
npv = round(100*cm[0, 0] / np.sum(cm[:, 0]), 2)

sen = np.zeros(len(cm)-1)
ppv = np.zeros(len(cm)-1)

for i in range(1, len(cm)):
    sen[i-1] = np.sum(cm[i, :])*(cm[i, i] / np.sum(cm[i, :]))
    ppv[i-1] = np.sum(cm[:, i])*(cm[i, i] / np.sum(cm[:, i]))

sen = round(100*np.sum(sen)/np.sum(cm[1:, :]), 2)
ppv = round(100*np.sum(ppv)/np.sum(cm[:, 1:]), 2)

print(accr, sen, spec, npv, ppv)


[88. 90.]
200
90.0 89.0 92.0 87.62 91.28


In [51]:
cm = np.array([[92, 8, 0], 
               [10, 90, 0], 
               [3, 97, 0]])

accr = round(100*np.trace(cm) / np.sum(cm), 2)
spec = round(100*cm[0, 0] / np.sum(cm[0, :]), 2)
npv = round(100*cm[0, 0] / np.sum(cm[:, 0]), 2)

sen = np.zeros(len(cm)-1)
ppv = np.zeros(len(cm)-1)

for i in range(1, len(cm)):
    sen[i-1] = np.sum(cm[i, :])*(cm[i, i] / np.sum(cm[i, :]))
    ppv[i-1] = np.sum(cm[:, i])*(cm[i, i] / np.sum(cm[:, i]))

print(ppv)
sen = round(100*np.sum(sen)/np.sum(cm[1:, :]), 2)
ppv = round(100*np.sum(ppv)/np.sum(cm[:, 1:]), 2)

print(accr, sen, spec, npv, ppv)


[90. nan]
60.67 45.0 92.0 87.62 nan


/home/yunseob/Pytorch/lib/python3.5/site-packages/ipykernel_launcher.py:14: RuntimeWarning: invalid value encountered in long_scalars
  


In [63]:
cm

array([[92,  8,  0],
       [10, 90,  0],
       [ 3, 97,  0]])

In [97]:
cm = np.array([[92, 8, 0], 
               [10, 90, 0], 
               [3, 97, 0]])

assert 0 not in np.sum(cm, axis = 0), 'Totally misclassified class exists'

accr = round(100*np.trace(cm) / np.sum(cm), 2)
spec = round(100*cm[0, 0] / np.sum(cm[0, :]), 2)
npv = round(100*cm[0, 0] / np.sum(cm[:, 0]), 2)

sen = np.zeros(len(cm)-1)
ppv = np.zeros(len(cm)-1)

for i in range(1, len(cm)):
    sen[i-1] = np.sum(cm[i, :])*(cm[i, i] / np.sum(cm[i, :]))
    ppv[i-1] = np.sum(cm[:, i])*(cm[i, i] / np.sum(cm[:, i]))

print(ppv)
sen = round(100*np.sum(sen)/np.sum(cm[1:, :]), 2)
ppv = round(100*np.sum(ppv)/np.sum(cm[:, 1:]), 2)

print(accr, sen, spec, npv, ppv)

AssertionError: Totally misclassified class exists

In [98]:
cm = np.array([[92, 5, 3], 
               [10, 88, 2], 
               [3, 7, 90]])

assert 0 not in np.sum(cm, axis = 0), 'Totally misclassified class exists'

accr = round(100*np.trace(cm) / np.sum(cm), 2)
spec = round(100*cm[0, 0] / np.sum(cm[0, :]), 2)
npv = round(100*cm[0, 0] / np.sum(cm[:, 0]), 2)

sen = np.zeros(len(cm)-1)
ppv = np.zeros(len(cm)-1)

for i in range(1, len(cm)):
    sen[i-1] = np.sum(cm[i, :])*(cm[i, i] / np.sum(cm[i, :]))
    ppv[i-1] = np.sum(cm[:, i])*(cm[i, i] / np.sum(cm[:, i]))

sen = round(100*np.sum(sen)/np.sum(cm[1:, :]), 2)
ppv = round(100*np.sum(ppv)/np.sum(cm[:, 1:]), 2)

print(accr, sen, spec, npv, ppv)

[88. 90.]
90.0 89.0 92.0 87.62 91.28


In [2]:
cm = np.array([[92, 5, 3, 0], 
               [10, 88, 0, 2], 
               [3, 1, 90, 6], 
               [0, 4, 4, 92]])

assert 0 not in np.sum(cm, axis = 0), 'Totally misclassified class exists'

accr = round(100*np.trace(cm) / np.sum(cm), 2)
spec = round(100*cm[0, 0] / np.sum(cm[0, :]), 2)
npv = round(100*cm[0, 0] / np.sum(cm[:, 0]), 2)

sen = np.zeros(len(cm)-1)
ppv = np.zeros(len(cm)-1)

for i in range(1, len(cm)):
    sen[i-1] = np.sum(cm[i, :])*(cm[i, i] / np.sum(cm[i, :]))
    ppv[i-1] = np.sum(cm[:, i])*(cm[i, i] / np.sum(cm[:, i]))

sen = round(100*np.sum(sen)/np.sum(cm[1:, :]), 2)
ppv = round(100*np.sum(ppv)/np.sum(cm[:, 1:]), 2)

print(accr, sen, spec, npv, ppv)

90.5 90.0 92.0 87.62 91.53


In [ ]:
assert 0 not in np.sum(self.cm, axis = 0), 'Totally misclassified class exists'

accr = round(100*np.trace(self.cm) / np.sum(self.cm), 2)
spec = round(100*self.cm[0, 0] / np.sum(self.cm[0, :]), 2)
npv = round(100*self.cm[0, 0] / np.sum(self.cm[:, 0]), 2)

sen = np.zeros(len(self.cm)-1)
ppv = np.zeros(len(self.cm)-1)

for i in range(1, len(self.cm)):
    sen[i-1] = np.sum(self.cm[i, :])*(self.cm[i, i] / np.sum(self.cm[i, :]))
    ppv[i-1] = np.sum(self.cm[:, i])*(self.cm[i, i] / np.sum(self.cm[:, i]))

sen = round(100*np.sum(sen)/np.sum(self.cm[1:, :]), 2)
ppv = round(100*np.sum(ppv)/np.sum(self.cm[:, 1:]), 2)

In [3]:
cm = np.array([[92, 8, 0], 
               [10, 90, 0], 
               [3, 97, 0]])

In [ ]:
np.sum()

In [3]:
cm = np.array([[92, 5, 3, 0], 
               [10, 88, 0, 2], 
               [3, 1, 90, 6], 
               [0, 4, 4, 92]])

# assert 0 not in np.sum(cm, axis = 0), 'Totally misclassified class exists'

accr = round(100*np.trace(cm) / np.sum(cm), 2)
spec = round(100*cm[0, 0] / np.sum(cm[0, :]), 2)
npv = round(100*cm[0, 0] / np.sum(cm[:, 0]), 2)

sen = np.zeros(len(cm)-1)
ppv = np.zeros(len(cm)-1)

for i in range(1, len(cm)):
    sen[i-1] = np.sum(cm[i, :])*(cm[i, i] / np.sum(cm[i, :]))
    if np.sum(cm[:, i]) > 0:
        ppv[i-1] = np.sum(cm[:, i])*(cm[i, i] / np.sum(cm[:, i]))
    elif np.sum(cm[:, i]) == 0:
        ppv[i-1] = 0

sen = round(100*np.sum(sen)/np.sum(cm[1:, :]), 2)
ppv = round(100*np.sum(ppv)/np.sum(cm[:, 1:]), 2)

print(accr, sen, spec, npv, ppv)

90.5 90.0 92.0 87.62 91.53


In [8]:
cm = np.array([[92, 8, 0, 0], 
               [10, 90, 0, 0], 
               [3, 97, 0, 0], 
              [0, 0, 100, 0]])

# assert 0 not in np.sum(cm, axis = 0), 'Totally misclassified class exists'

if 0 in np.sum(cm, axis = 0):
    print('Totally misclassified class exists')

accr = round(100*np.trace(cm) / np.sum(cm), 2)
spec = round(100*cm[0, 0] / np.sum(cm[0, :]), 2)
npv = round(100*cm[0, 0] / np.sum(cm[:, 0]), 2)

sen = np.zeros(len(cm)-1)
ppv = np.zeros(len(cm)-1)

for i in range(1, len(cm)):
    sen[i-1] = np.sum(cm[i, :])*(cm[i, i] / np.sum(cm[i, :]))
    if np.sum(cm[:, i]) > 0:
        ppv[i-1] = np.sum(cm[:, i])*(cm[i, i] / np.sum(cm[:, i]))
    elif np.sum(cm[:, i]) == 0:
        ppv[i-1] = 0

sen = round(100*np.sum(sen)/np.sum(cm[1:, :]), 2)
ppv = round(100*np.sum(ppv)/np.sum(cm[:, 1:]), 2)

print(accr, sen, spec, npv, ppv)

Totally misclassified class exists
45.5 30.0 92.0 87.62 30.51
